#!/usr/bin/env python3
"""Build a single-file, dependency-free worker that can be pasted into the
Cloudflare dashboard.

    python3 tools/build_worker.py   ->  chatbot/worker/worker-standalone.js

Why this exists
---------------
The TypeScript worker in chatbot/worker/src is the better artefact to read: it
is typed, split into modules, and uses the official SDK. But deploying it needs
Node, npm and wrangler on someone's machine.

The person deploying this runs a Thai restaurant. Requiring a working JavaScript
toolchain to change what a chatbot is allowed to say is a governance problem
wearing a convenience problem's clothes: if deployment is hard it gets done
rarely, by one person, without review, and eventually not at all.

So this emits one file with no imports - the rules, the knowledge base and the
whole worker inlined - which deploys by pasting into a web page. The SDK is
replaced by a plain fetch and about thirty lines of SSE parsing.

Both workers are generated from the same approved sources, so they cannot
disagree about what the assistant may say. Re-run this whenever the rules or
the knowledge base change.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "chatbot", "worker", "worker-standalone.js")


def const_from_ts(filename, name):
    """Read a generated constant, so the standalone build cannot drift from the
    approved rules by being edited independently."""
    path = os.path.join(ROOT, "chatbot", "worker", "src", filename)
    try:
        with open(path, encoding="utf-8") as fh:
            src = fh.read()
    except FileNotFoundError:
        sys.exit("%s is missing - run tools/build_kb.py first" % path)
    m = re.search(r"export const %s = (\".*\");" % name, src, re.S)
    if not m:
        sys.exit("could not read %s from %s - run tools/build_kb.py first" % (name, filename))
    return json.loads(m.group(1))


TEMPLATE = '''// Ari Thai Catering - chat worker (standalone build).
//
// GENERATED by tools/build_worker.py from the approved rules and the knowledge
// base. Do not edit here: edit chatbot/system-rules.md or the source content,
// then re-run tools/build_kb.py && tools/build_worker.py.
//
// Deploy by pasting this whole file into the Cloudflare dashboard worker editor,
// then adding ANTHROPIC_API_KEY as an encrypted variable and ALLOWED_ORIGINS as
// a plain one. No build step, no dependencies, no command line.
//
// Remember that variables bind at DEPLOY time. Setting one in the dashboard and
// not pressing Deploy again leaves the worker running the previous config while
// the screen shows the new one.
//
// It exists for one reason: a static site cannot keep a secret. Everything else
// it does - origin allowlist, rate limit, input caps - follows from the fact
// that this URL is public and every request costs money.

const SYSTEM_RULES = __RULES__;

const KNOWLEDGE_BASE = __KB__;

// Caps bound the damage from one abusive caller. The spend limit in the
// Anthropic console is the real backstop.
const LIMITS = { messages: 24, chars: 1000, totalChars: 8000, maxTokens: 700 };
const DEFAULT_MODEL = "claude-haiku-4-5";

// The cache breakpoint goes at the end of the fixed prefix: rules and knowledge
// base are identical on every request, so after the first turn they are re-read
// at cache rates. Anything per-request must come after this, never inside it.
function buildSystem() {
  return [
    { type: "text", text: SYSTEM_RULES },
    {
      type: "text",
      text: "# KNOWLEDGE BASE\\n\\nEverything you are allowed to state as fact:\\n\\n" + KNOWLEDGE_BASE,
      cache_control: { type: "ephemeral" },
    },
  ];
}

// Who is allowed to use this worker.
//
// FAILS CLOSED: an unset or empty ALLOWED_ORIGINS refuses everything rather
// than accepting everything. A worker that accepts any origin and logs a
// warning looks identical to a protected one from the dashboard - the control
// is specified but not in force, and only an external probe can tell.
//
// What it does: stops another WEBSITE pointing its widget at this worker,
// because browsers send Origin and enforce the response. What it does not do:
// stop a script, which can send any Origin it likes. The backstop for that is
// the spend cap on the API key.
function corsHeaders(request, env) {
  const list = (env.ALLOWED_ORIGINS || "").split(",").map((o) => o.trim()).filter(Boolean);
  if (list.length === 0) {
    console.error("ALLOWED_ORIGINS is not set - refusing all requests");
    return null;
  }
  const origin = request.headers.get("Origin");
  if (!origin || !list.includes(origin)) return null;
  return { "Access-Control-Allow-Origin": origin, Vary: "Origin" };
}

function json(body, status, headers) {
  return new Response(JSON.stringify(body), {
    status,
    headers: { "Content-Type": "application/json", ...(headers || {}) },
  });
}

function parseMessages(body) {
  if (typeof body !== "object" || body === null) return "Body must be a JSON object.";
  const raw = body.messages;
  if (!Array.isArray(raw) || raw.length === 0) return "messages must be a non-empty array.";
  if (raw.length > LIMITS.messages) return "Conversation is too long.";
  const out = [];
  let total = 0;
  for (const m of raw) {
    if (typeof m !== "object" || m === null) return "Each message must be an object.";
    if (m.role !== "user" && m.role !== "assistant") return "role must be user or assistant.";
    if (typeof m.content !== "string") return "content must be a string.";
    const text = m.content.trim();
    if (!text) return "content must not be empty.";
    if (text.length > LIMITS.chars) return "That message is too long - please shorten it.";
    total += text.length;
    if (total > LIMITS.totalChars) return "Conversation is too long.";
    out.push({ role: m.role, content: text });
  }
  if (out[out.length - 1].role !== "user") return "The last message must be from the user.";
  return out;
}

export default {
  async fetch(request, env) {
    const cors = corsHeaders(request, env);
    if (cors === null) return json({ error: "Origin not allowed." }, 403);

    if (request.method === "OPTIONS") {
      return new Response(null, {
        status: 204,
        headers: {
          ...cors,
          "Access-Control-Allow-Methods": "POST, OPTIONS",
          "Access-Control-Allow-Headers": "Content-Type",
          "Access-Control-Max-Age": "86400",
        },
      });
    }

    const url = new URL(request.url);
    if (url.pathname === "/health") return json({ ok: true, model: env.MODEL || DEFAULT_MODEL }, 200, cors);
    if (request.method !== "POST" || url.pathname !== "/chat") {
      return json({ error: "POST /chat" }, 404, cors);
    }

    // Per-IP rate limiting, if the binding exists.
    //
    // This one cannot fail closed the way the origin check does: refusing all
    // traffic when the limiter is missing is a self-inflicted outage, which is
    // worse than the risk it defends against. So it fails open - but LOUDLY,
    // and the log line names the control that is absent. A control that goes
    // missing silently is the one discovered during the incident.
    //
    // If you see this in the logs, add a Rate limiting binding named
    // RATE_LIMITER in the dashboard. Until then the spend cap is the only thing
    // bounding abuse.
    if (env.RATE_LIMITER) {
      const ip = request.headers.get("CF-Connecting-IP") || "unknown";
      const { success } = await env.RATE_LIMITER.limit({ key: ip });
      if (!success) {
        console.log(JSON.stringify({ ari_metric: "rate_limited" }));
        return json({ error: "Too many messages. Please wait a moment." }, 429, cors);
      }
    } else {
      console.error("RATE_LIMITER binding is missing - requests are NOT rate limited");
    }

    let body;
    try {
      body = await request.json();
    } catch {
      return json({ error: "Invalid JSON." }, 400, cors);
    }
    const messages = parseMessages(body);
    if (typeof messages === "string") return json({ error: messages }, 400, cors);

    if (!env.ANTHROPIC_API_KEY) {
      console.error("ANTHROPIC_API_KEY is not set");
      return json({ error: "The assistant is not configured." }, 500, cors);
    }

    // Usage metric - privacy-safe by construction. A label, the turn number and
    // a coarse language flag; NEVER any message text. Customers paste
    // colleagues' allergies into this box; storing that is a privacy obligation
    // the business is not set up to carry (RISKS.md R12).
    try {
      const last = messages[messages.length - 1].content;
      console.log(JSON.stringify({
        ari_metric: "chat",
        turn: messages.filter((m) => m.role === "user").length,
        lang: /[\\u0E00-\\u0E7F]/.test(last) ? "th" : "other",
      }));
    } catch (_) { /* metrics must never break a reply */ }

    const upstream = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "content-type": "application/json",
        "x-api-key": env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: env.MODEL || DEFAULT_MODEL,
        max_tokens: LIMITS.maxTokens,
        system: buildSystem(),
        messages,
        stream: true,
      }),
    });

    const encoder = new TextEncoder();

    // The worker speaks its own protocol rather than passing the provider's
    // event stream through. The widget therefore knows nothing about the model,
    // the SDK or the event schema - any of which can change without touching
    // front-end code. It also lets an error be delivered mid-stream, after the
    // answer has started, which an HTTP status code cannot do.
    const stream = new ReadableStream({
      async start(controller) {
        const send = (e) => controller.enqueue(encoder.encode("data: " + JSON.stringify(e) + "\\n\\n"));

        if (!upstream.ok || !upstream.body) {
          console.error("upstream " + upstream.status);
          console.log(JSON.stringify({ ari_metric: "error" }));
          send({ type: "error", message: __FALLBACK__ });
          controller.close();
          return;
        }

        const reader = upstream.body.getReader();
        const decoder = new TextDecoder();
        let buffer = "";
        let usage = null;

        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;
            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split("\\n");
            buffer = lines.pop() || "";
            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed.startsWith("data:")) continue;
              let event;
              try {
                event = JSON.parse(trimmed.slice(5));
              } catch {
                continue;
              }
              if (event.type === "content_block_delta" && event.delta && event.delta.type === "text_delta") {
                send({ type: "text", text: event.delta.text });
              } else if (event.type === "message_delta" && event.usage) {
                usage = event.usage;
              }
            }
          }
          // Token counts only. No conversation content is stored anywhere.
          if (usage) console.log(JSON.stringify(usage));
          send({ type: "done" });
        } catch (err) {
          console.error("stream failed", err);
          send({ type: "error", message: __FALLBACK__ });
        } finally {
          controller.close();
        }
      },
    });

    return new Response(stream, {
      headers: {
        ...cors,
        "Content-Type": "text/event-stream; charset=utf-8",
        "Cache-Control": "no-store",
        Connection: "keep-alive",
      },
    });
  },
};
'''

FALLBACK = ("Sorry, something went wrong at our end. Please email us at "
            "arithaistreetfood@gmail.com and we'll come straight back to you.")


def main():
    rules = const_from_ts("system-rules.ts", "SYSTEM_RULES")
    kb = const_from_ts("knowledge-base.ts", "KNOWLEDGE_BASE")
    js = (TEMPLATE
          .replace("__RULES__", json.dumps(rules))
          .replace("__KB__", json.dumps(kb))
          .replace("__FALLBACK__", json.dumps(FALLBACK)))
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(js)
    print("chatbot/worker/worker-standalone.js   %6.1f KB  (paste this into Cloudflare)"
          % (len(js) / 1024))


if __name__ == "__main__":
    main()
