#!/usr/bin/env python3
"""Generate the assistant's knowledge base from the owner's source of truth.

    python3 tools/build_kb.py

Reads:
    catering-facts.json     the owner's catering facts (see its _readme)
    chatbot/system-rules.md the approved behavioural contract

Writes:
    chatbot/knowledge-base.md              human-readable, for owner review
    chatbot/worker/src/knowledge-base.ts   the same text, bundled into the worker
    chatbot/worker/src/system-rules.ts     the rules, bundled into the worker

Why generate rather than write
------------------------------
The assistant must not be able to state a price the business does not charge.
Making the knowledge base a *derived* artefact means there is exactly one place
to change a fact, and the generated files are checked in CI against their
source - so a knowledge base that has drifted fails the build rather than
answering a customer.

The generated files are committed so the worker can be deployed from a clean
checkout with no Python. Re-run this after editing either input, then run
tools/build_worker.py.
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FACTS = os.path.join(ROOT, "catering-facts.json")
RULES_MD = os.path.join(ROOT, "chatbot", "system-rules.md")
OUT_MD = os.path.join(ROOT, "chatbot", "knowledge-base.md")
OUT_KB_TS = os.path.join(ROOT, "chatbot", "worker", "src", "knowledge-base.ts")
OUT_RULES_TS = os.path.join(ROOT, "chatbot", "worker", "src", "system-rules.ts")


def read_rules():
    """The behavioural rules, minus the HTML comment header and the approval
    record. The approval table is governance metadata for people, not
    instructions for the model - shipping it would waste tokens and invite the
    assistant to talk about its own approval status."""
    text = open(RULES_MD, encoding="utf-8").read()
    text = re.sub(r"^<!--.*?-->\s*", "", text, flags=re.S)
    text = text.split("\n---\n\n## Approval record")[0]
    return text.strip()


def kb_from(f):
    b, o, d, dl, food = f["business"], f["ordering"], f["dietary"], f["delivery"], f["food"]
    L = []
    add = L.append

    add("# %s - assistant knowledge base" % b["name"])
    add("")
    add("Generated by tools/build_kb.py from catering-facts.json. Do not edit by hand.")
    add("")

    add("## The business")
    add("- %s is the catering side of %s." % (b["name"], b["parent"]))
    add("- Address: %s" % b["address"])
    add("- Email: %s" % b["email"])
    add("- Phone: %s" % b["phone"])
    add("- The restaurant is open %s." % b["restaurant_hours"])
    add("- We cater: %s." % ", ".join(b["caters"]))
    add("- %s" % b["scope_note"])
    add("")

    add("## Packages")
    add(f["price_note"])
    add("")
    for p in f["packages"]:
        add("- %s: $%s per person, %s." % (p["tier"], p["price"], p["gst"]))
    add("")
    add("These packages have no names beyond the descriptions above. Do not invent a name for one.")
    add("")

    add("## Ordering")
    add("- Minimum order: %d people." % o["minimum_people"])
    add("- Notice required: at least %d hours." % o["notice_hours"])
    add("- We cater up to %s." % o["typical_maximum"])
    add("- %s" % o["over_maximum"])
    add("- How to order: %s" % o["how_to_order"])
    add("- Payment: %s" % o["payment"])
    add("- Deposit: %s" % o["deposit"])
    add("- Changes: %s" % o["changes"])
    add("- Cancellation: %s" % o["cancellation"])
    add("")

    add("## Delivery and pick-up")
    add("- Delivery hours: %s." % dl["hours"])
    add("- %s" % dl["free_area"])
    add("- %s" % dl["outside_area"])
    add("- %s" % dl["timing"])
    add("- %s" % dl["in_building"])
    add("- %s" % dl["pickup"])
    add("")

    add("## The food")
    add("- %s" % food["style"])
    add("- Popular dishes: %s." % ", ".join(food["popular_dishes"]))
    add("- %s" % food["availability_note"])
    add("- These are the only dishes you may name. If someone asks about a dish that is not on this list, say you do not have that detail and ask them to email us.")
    for a in food["add_ons"]:
        add("- %s" % a)
    add("- Packaging: %s" % " ".join(food["packaging"]))
    add("- %s" % food["mixed_choices"])
    add("- %s" % food["desserts_drinks"])
    add("")

    add("## Dietary requirements and allergies")
    add("- %s" % d["options"])
    add("- %s" % d["ingredients"])
    add("- %s" % d["cross_contamination"])
    add("- Say this in any answer that touches dietary requirements or allergies: \"%s\"" % d["always_say"])
    add("- You may say a choice is available as vegan, vegetarian or gluten-free. You may never say a dish is free of an allergen, and never that it is safe for anyone.")
    add("")

    add("## Questions we are asked often")
    add("")
    for q, a in f["faqs"]:
        add("**%s**" % q)
        add(a)
        add("")

    add("## Note")
    add(f["closing_note"])
    return "\n".join(L).rstrip() + "\n"


def emit_ts(path, name, text, source):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(
            "// Generated by tools/build_kb.py - do not edit.\n"
            "// Source of truth is %s.\n"
            "export const %s = %s;\n" % (source, name, json.dumps(text))
        )


def main():
    if not os.path.exists(FACTS):
        sys.exit("%s is missing" % FACTS)
    facts = json.load(open(FACTS, encoding="utf-8"))
    kb = kb_from(facts)
    rules = read_rules()

    os.makedirs(os.path.dirname(OUT_MD), exist_ok=True)
    with open(OUT_MD, "w", encoding="utf-8") as fh:
        fh.write(kb)
    emit_ts(OUT_KB_TS, "KNOWLEDGE_BASE", kb, "catering-facts.json")
    emit_ts(OUT_RULES_TS, "SYSTEM_RULES", rules, "chatbot/system-rules.md")

    words = len((kb + rules).split())
    print("chatbot/knowledge-base.md            %6.1f KB" % (len(kb) / 1024))
    print("chatbot/worker/src/knowledge-base.ts %6.1f KB" % (len(kb) / 1024))
    print("chatbot/worker/src/system-rules.ts   %6.1f KB" % (len(rules) / 1024))
    print("\nSystem prompt is ~%d words, roughly %d tokens, cached after the first turn."
          % (words, words * 4 // 3))
    print("Now run: python3 tools/build_worker.py")


if __name__ == "__main__":
    main()
